"""empty message

Revision ID: 001e393a37ab
Revises: d2fdd14f98af
Create Date: 2017-06-17 21:26:28.415737

"""

# revision identifiers, used by Alembic.
revision = '001e393a37ab'
down_revision = 'd2fdd14f98af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fq_report_prop', 'req_filter1')
    op.drop_column('fq_report_prop', 'is_filter1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fq_report_prop', sa.Column('is_filter1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fq_report_prop', sa.Column('req_filter1', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
