"""empty message

Revision ID: 0fa006f108bf
Revises: 422e10d1db6b
Create Date: 2017-06-17 21:17:38.902373

"""

# revision identifiers, used by Alembic.
revision = '0fa006f108bf'
down_revision = '422e10d1db6b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fq_report_prop', sa.Column('is_filter', sa.Integer(), nullable=True))
    op.add_column('fq_report_prop', sa.Column('req_filter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fq_report_prop', 'req_filter')
    op.drop_column('fq_report_prop', 'is_filter')
    # ### end Alembic commands ###
