"""empty message

Revision ID: 400aadfbaaac
Revises: 3370509f0992
Create Date: 2017-06-17 21:21:28.265857

"""

# revision identifiers, used by Alembic.
revision = '400aadfbaaac'
down_revision = '3370509f0992'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fq_report_prop', 'req_filter')
    op.drop_column('fq_report_prop', 'is_filter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fq_report_prop', sa.Column('is_filter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fq_report_prop', sa.Column('req_filter', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
