"""empty message

Revision ID: 422e10d1db6b
Revises: 94c8a3b2507d
Create Date: 2017-06-17 21:16:36.885118

"""

# revision identifiers, used by Alembic.
revision = '422e10d1db6b'
down_revision = '94c8a3b2507d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fq_report_prop', 'req_filter')
    op.drop_column('fq_report_prop', 'is_filter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fq_report_prop', sa.Column('is_filter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('fq_report_prop', sa.Column('req_filter', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
