"""empty message

Revision ID: 9b04bbc35a85
Revises: 74732c4a9e0a
Create Date: 2017-05-28 22:28:00.469973

"""

# revision identifiers, used by Alembic.
revision = '9b04bbc35a85'
down_revision = '74732c4a9e0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exec_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exec_run_detail',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('sql_text', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('run_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exec_run_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('exec_id', sa.String(length=32), nullable=True),
    sa.Column('data_source', sa.String(length=30), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('create_by', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_data_source',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('db_connect', sa.String(length=300), nullable=True),
    sa.Column('ds_type', sa.String(length=32), nullable=True),
    sa.Column('ds_group', sa.String(length=32), nullable=True),
    sa.Column('pool_min', sa.Integer(), nullable=True),
    sa.Column('pool_max', sa.Integer(), nullable=True),
    sa.Column('pool_step', sa.Integer(), nullable=True),
    sa.Column('sys_creation_date', sa.DateTime(), nullable=True),
    sa.Column('sys_last_modified_date', sa.DateTime(), nullable=True),
    sa.Column('sys_last_modified_by', sa.String(length=30), nullable=True),
    sa.Column('sys_create_by', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('sys_id_generator',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('start_num', sa.BigInteger(), nullable=True),
    sa.Column('end_num', sa.BigInteger(), nullable=True),
    sa.Column('current_num', sa.BigInteger(), nullable=True),
    sa.Column('prefix', sa.String(length=30), nullable=True),
    sa.Column('postfix', sa.String(length=30), nullable=True),
    sa.Column('seq_len', sa.Integer(), nullable=True),
    sa.Column('fill_char', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_id_generator')
    op.drop_table('sys_data_source')
    op.drop_table('exec_run_log')
    op.drop_table('exec_run_detail')
    op.drop_table('exec_history')
    # ### end Alembic commands ###
