"""empty message

Revision ID: a270975da151
Revises: 9b04bbc35a85
Create Date: 2017-06-03 15:20:30.251082

"""

# revision identifiers, used by Alembic.
revision = 'a270975da151'
down_revision = '9b04bbc35a85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_code_type',
    sa.Column('type_id', sa.String(length=30), nullable=False),
    sa.Column('type_name', sa.String(length=30), nullable=True),
    sa.Column('parent_type_id', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('sys_code_value',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('type_id', sa.String(length=30), nullable=True),
    sa.Column('value_id', sa.String(length=30), nullable=True),
    sa.Column('value_name', sa.String(length=30), nullable=True),
    sa.Column('parent_id', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_selection',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('datasource', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user_activity',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('activity_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_grp_role_map',
    sa.Column('user_grp_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('user_grp_id', 'role_id')
    )
    op.create_table('user_list',
    sa.Column('login_name', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('user_password', sa.String(length=64), nullable=True),
    sa.Column('pwd_exp_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('user_grp_id', sa.String(length=32), nullable=True),
    sa.Column('email_address', sa.String(length=64), nullable=True),
    sa.Column('session_token', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_session', sa.DateTime(), nullable=True),
    sa.Column('org_name', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('login_name')
    )
    op.create_table('user_role',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role_template',
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('activity_id', sa.String(length=64), nullable=False),
    sa.Column('access_level', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('role_id', 'activity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_template')
    op.drop_table('user_role')
    op.drop_table('user_list')
    op.drop_table('user_grp_role_map')
    op.drop_table('user_group')
    op.drop_table('user_activity')
    op.drop_table('sys_selection')
    op.drop_table('sys_code_value')
    op.drop_table('sys_code_type')
    # ### end Alembic commands ###
