"""empty message

Revision ID: be0e9f228cfa
Revises: None
Create Date: 2017-06-15 21:13:57.261958

"""

# revision identifiers, used by Alembic.
revision = 'be0e9f228cfa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_code_type',
    sa.Column('type_id', sa.String(length=30), nullable=False),
    sa.Column('type_name', sa.String(length=30), nullable=True),
    sa.Column('parent_type_id', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('sys_code_value',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('type_id', sa.String(length=30), nullable=True),
    sa.Column('value_id', sa.String(length=30), nullable=True),
    sa.Column('value_name', sa.String(length=30), nullable=True),
    sa.Column('parent_id', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_selection',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('datasource', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.alter_column('sys_id_generator', 'seq_len',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_id_generator', 'seq_len',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('sys_selection')
    op.drop_table('sys_code_value')
    op.drop_table('sys_code_type')
    # ### end Alembic commands ###
