"""empty message

Revision ID: d0bdca341c18
Revises: be0e9f228cfa
Create Date: 2017-06-17 21:00:16.925452

"""

# revision identifiers, used by Alembic.
revision = 'd0bdca341c18'
down_revision = 'be0e9f228cfa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fq_download_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('exp_id', sa.String(length=32), nullable=True),
    sa.Column('download_date', sa.DateTime(), nullable=True),
    sa.Column('download_by', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fq_export_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rpt_id', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('query_end_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('total_cnt', sa.Integer(), nullable=True),
    sa.Column('exp_type', sa.String(length=10), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('export_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fq_folder_tree',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fq_report_prop',
    sa.Column('rpt_id', sa.String(length=32), nullable=False),
    sa.Column('col_name', sa.String(length=30), nullable=False),
    sa.Column('data_type', sa.String(length=30), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('is_filter', sa.Boolean(), nullable=True),
    sa.Column('req_filter', sa.Boolean(), nullable=True),
    sa.Column('filter_type', sa.String(length=32), nullable=True),
    sa.Column('selection', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rpt_id', 'col_name')
    )
    op.create_table('fq_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('rpt_desc', sa.String(length=300), nullable=True),
    sa.Column('folder_id', sa.String(length=32), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('datasource', sa.String(length=32), nullable=True),
    sa.Column('sys_ent_status', sa.String(length=10), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('my_index', 'fq_reports', ['name', 'folder_id'], unique=True)
    op.create_table('fq_ud_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rpt_id', sa.String(length=32), nullable=True),
    sa.Column('owner', sa.String(length=32), nullable=True),
    sa.Column('folder_id', sa.String(length=32), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fq_ud_reports_detail',
    sa.Column('ud_rpt_id', sa.String(length=32), nullable=False),
    sa.Column('ud_type', sa.String(length=32), nullable=False),
    sa.Column('ud_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ud_rpt_id', 'ud_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fq_ud_reports_detail')
    op.drop_table('fq_ud_reports')
    op.drop_index('my_index', table_name='fq_reports')
    op.drop_table('fq_reports')
    op.drop_table('fq_report_prop')
    op.drop_table('fq_folder_tree')
    op.drop_table('fq_export_log')
    op.drop_table('fq_download_log')
    # ### end Alembic commands ###
