"""empty message

Revision ID: d2fdd14f98af
Revises: 400aadfbaaac
Create Date: 2017-06-17 21:21:58.833019

"""

# revision identifiers, used by Alembic.
revision = 'd2fdd14f98af'
down_revision = '400aadfbaaac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fq_report_prop', sa.Column('is_filter', sa.Boolean(), nullable=True))
    op.add_column('fq_report_prop', sa.Column('req_filter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fq_report_prop', 'req_filter')
    op.drop_column('fq_report_prop', 'is_filter')
    # ### end Alembic commands ###
