"""empty message

Revision ID: ea9c782f5978
Revises: d0bdca341c18
Create Date: 2017-06-17 21:10:44.289904

"""

# revision identifiers, used by Alembic.
revision = 'ea9c782f5978'
down_revision = 'd0bdca341c18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fq_report_prop', 'is_filter')
    op.drop_column('fq_report_prop', 'req_filter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fq_report_prop', sa.Column('req_filter', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('fq_report_prop', sa.Column('is_filter', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
